### ISSUE TITLE
IndexError: The shape of the mask [322] at index 0 does not match the shape of the indexed tensor [424, 50] at index 0

### ISSUE THREAD

**Issue by Zerohertz** [bytedance/SPTSv2#4]
When training `SPTSv2` with customized data, an `IndexError` occurred as follows.

```python
Traceback (most recent call last):
  File "main.py", line 267, in <module>
    main(args)
  File "main.py", line 229, in main
    args.clip_max_norm, learning_rate_schedule, args.print_freq, args.max_length)
  File "/SPTSv2/engine_sptsv2.py", line 32, in train_one_epoch
    for samples, input_box_seqs, input_label_seqs, output_box_seqs, output_label_seqs in metric_logger.log_every(data_loader, print_freq, header):
  File "/SPTSv2/util/misc_sptsv2.py", line 219, in log_every
    for obj in iterable:
  File "/opt/conda/envs/sptsv2/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/opt/conda/envs/sptsv2/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/opt/conda/envs/sptsv2/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/opt/conda/envs/sptsv2/lib/python3.7/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/envs/sptsv2/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/envs/sptsv2/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/envs/sptsv2/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/SPTSv2/datasets/ocr_dataset.py", line 34, in __getitem__
    img1, target1 = self._transforms(img, target)
  File "/SPTSv2/datasets/sptsv2_transforms.py", line 352, in __call__
    image, target = t(image, target)
  File "/SPTSv2/datasets/sptsv2_transforms.py", line 246, in __call__
    img_, target_ = crop(img.copy(), target.copy(), region)
  File "/SPTSv2/datasets/sptsv2_transforms.py", line 75, in crop
    target[field] = target[field][keep]
IndexError: The shape of the mask [322] at index 0 does not match the shape of the indexed tensor [424, 50] at index 0
```

I guess `keep` is causing that issue

**Comment by zhangjx123** [comment]
it may be caused by the incorrect gt shape, so you can check the shape of 'bezier_pts' or 'center_pts' or others

**Comment by Zerohertz** [comment]
Thank you for your comment.

As you said, it seems to be a problem with GT. However, it seems to be a problem caused by augmenting the data using the `keep` variable.
If I'm wrong, is this fix https://github.com/Zerohertz/SPTSv2/commit/45da8808a2ead238e67d2cf91dd611c69613bf63 wrong?

**Comment by Zerohertz** [comment]
In this line of error logs, I guessed that there was a problem on the recog side of the GT.

```python
IndexError: The shape of the mask [322] at index 0 does not match the shape of the indexed tensor [424, 50] at index 0
```

This is because you set `max_length` to 50.

**Comment by zhangjx123** [comment]
Hello, I only set max_length to 25 in English spotting task, never set 50. So I am confused about that, but it seems may be caused by recognition gt. The [keep] is just used for filterring dirty data out, so I think it can't solve this problem. I advise you to check the shape of input gts firstly~Thanks for your support.
